url: "https://ericasousaa.github.io"
baseurl: "/EricaSousa"

# Site settings
title: "Erica Sousa"
email: "seu-email@exemplo.com"
description: "Portfólio de projetos em Machine Learning, Visão Computacional e Desenvolvimento."

# Team / sobre você (pode usar só um ou remover os outros)
people:
- name: Erica Sousa
  pic: 1
  position: Desenvolvedora & Estagiária de Machine Learning
  social:
    - title: github
      url: https://github.com/ericasousaa
    - title: linkedin
      url: https://www.linkedin.com/in/seu-linkedin
    - title: twitter
      url: #

# Redes sociais (no rodapé)
social:
  - title: github
    url: https://github.com/ericasousaa
  - title: linkedin
    url: https://www.linkedin.com/in/seu-linkedin

# Build settings
markdown: kramdown
permalink: pretty
